package io.github.moneymaker26754.agentforge.core;

public enum EventType {
    SESSION_STARTED,
    MODEL_RESPONSE,
    CONTEXT_COMPRESSED,
    PHASE_ENTERED,
    VALIDATION_FAILED,
    APPROVAL_REQUESTED,
    APPROVAL_DECIDED,
    APPROVAL_PENDING,
    TOOL_INTENT,
    TOOL_RESULT,
    SESSION_COMPLETED,
    SESSION_TERMINATED
}

